Repository sktime/pytorch-forecasting, pull requests merged in 2020-11, with the labels that each got.

#115 Adding DeepAR and GPU fixes
  .pre-commit-config.yaml
  README.md
  pytorch_forecasting/__init__.py
  pytorch_forecasting/data/encoders.py
  pytorch_forecasting/data/timeseries.py
  pytorch_forecasting/metrics.py
  pytorch_forecasting/models/__init__.py
  pytorch_forecasting/models/base_model.py
  pytorch_forecasting/models/deepar/__init__.py
  pytorch_forecasting/models/nbeats/__init__.py
  pytorch_forecasting/models/temporal_fusion_transformer/__init__.py
  tests/test_data.py
  tests/test_metrics.py
  tests/test_models/conftest.py
  tests/test_models/test_deepar.py
Labels: work in progress

#153 Feature/support gru cells in deepar
  pytorch_forecasting/models/deepar/__init__.py
  pytorch_forecasting/models/deepar/sub_modules.py
  tests/test_models/test_deepar.py
Labels: enhancement

#173 Bugfix/basemodel handles non tensor raw predictions
  pytorch_forecasting/models/base_model.py
Labels: bug, enhancement

#179 Allow encoder normalizer for any covariate
  pytorch_forecasting/data/encoders.py
  pytorch_forecasting/data/timeseries.py
  tests/test_data.py
Labels: enhancement
