Repository sktime/pytorch-forecasting, pull requests merged in 2024-09, with the labels that each got.

#1650 [MNT] clean up and comment dep sets in `pyproject.toml`, remove unused `graph` dep set from CI
  .github/workflows/test.yml
  pyproject.toml
Labels: maintenance

#1629 [MNT] isolate `optuna` and `statsmodels` as soft dependencies
  pyproject.toml
  pytorch_forecasting/models/temporal_fusion_transformer/tuning.py
  tests/test_models/test_temporal_fusion_transformer.py
Labels: dependencies, maintenance

#1643 [DOC] various code formatting improvements
  pytorch_forecasting/metrics/distributions.py
Labels: documentation

#1636 [MNT] isolate `matplotlib` as soft dependency
  .github/workflows/test.yml
  pyproject.toml
  pytorch_forecasting/data/timeseries.py
  pytorch_forecasting/models/base_model.py
  pytorch_forecasting/models/nbeats/__init__.py
  pytorch_forecasting/models/nhits/__init__.py
  pytorch_forecasting/models/temporal_fusion_transformer/__init__.py
  pytorch_forecasting/utils/_dependencies.py
  tests/test_models/test_nbeats.py
  tests/test_models/test_nhits.py
  tests/test_models/test_temporal_fusion_transformer.py
Labels: dependencies, maintenance

#1641 [MNT] isolate `pytorch-optimizer` as soft dependency
  pyproject.toml
  pytorch_forecasting/models/base_model.py
Labels: dependencies, maintenance

#1646 [MNT]Remove `.env` file (we shouldn't be pushing the `.env` file
  .env
  .gitignore
Labels: maintenance

#1653 [MNT] update python version in release workflow to 3.11
  .github/workflows/pypi_release.yml
Labels: maintenance

#1656 [MNT] pypi release only on GH release
  .github/workflows/pypi_release.yml
Labels: maintenance

#1655 Fix/ar-tutorial
  docs/source/tutorials/ar.ipynb
Labels: bug

#1649 fix: Add outline to dark logo
  docs/source/_static/logo.svg
Labels: documentation

#1657 [MNT] improved release workflow
  .github/workflows/pypi_release.yml
Labels: maintenance

#1658 [DOC] improved readme links
  README.md
Labels: documentation

#1652 Release 1.1.0
  CHANGELOG.md
  pyproject.toml
  pytorch_forecasting/__init__.py
Labels: maintenance, release

#1659 [MNT] changelog generator script and release workflow improvement
  .github/workflows/pypi_release.yml
  build_tools/changelog.py
Labels: maintenance, release

#1648 [MNT] handle `mps backend` for lower versions of pytorch and fix `mps` failure on `macOS-latest` runner
  .github/workflows/test.yml
  pytorch_forecasting/utils/_utils.py
  tests/conftest.py
Labels: maintenance

#1673 [MNT] updates the actions in the doc build CI
  .github/workflows/test.yml
Labels: maintenance

#1676 [MNT] fixes to `readthedocs.yml`
  .readthedocs.yml
  pyproject.toml
Labels: documentation, maintenance

#1674 [DOC] update URLs to `sktime` org
  README.md
  docs/source/_static/custom.css
  docs/source/conf.py
  docs/source/index.rst
Labels: documentation, maintenance

#1688 [MNT] `show_versions` utility
  pytorch_forecasting/__init__.py
  pytorch_forecasting/utils/_maint/__init__.py
  pytorch_forecasting/utils/_maint/_show_versions.py
  tests/test_utils/test_show_versions.py
Labels: maintenance
