Repository sktime/pytorch-forecasting, pull requests merged in 2024-12, with the labels that each got.

#1720 [DOC] Updated documentation on `TimeSeriesDataSet.predict_mode`
  pytorch_forecasting/data/timeseries.py
Labels: documentation

#1739 [ENH] refactor `__init__` modules to no longer contain classes - preparatory commit
  pytorch_forecasting/models/deepar/_deepar.py
  pytorch_forecasting/models/mlp/_decodermlp.py
  pytorch_forecasting/models/nbeats/_nbeats.py
  pytorch_forecasting/models/nhits/_nhits.py
  pytorch_forecasting/models/rnn/_rnn.py
  pytorch_forecasting/models/temporal_fusion_transformer/_tft.py
Labels: enhancement

#1738 [ENH] refactor `__init__` modules to no longer contain classes
  pytorch_forecasting/models/deepar/__init__.py
  pytorch_forecasting/models/mlp/__init__.py
  pytorch_forecasting/models/nbeats/__init__.py
  pytorch_forecasting/models/nhits/__init__.py
  pytorch_forecasting/models/rnn/__init__.py
  pytorch_forecasting/models/temporal_fusion_transformer/__init__.py
Labels: enhancement

#1737 [ENH] extend package author attribution requirement in license to present
  LICENSE
Labels: enhancement

#1740 [MNT] update linting: limit line length to 88, add `isort`
  build_tools/changelog.py
  docs/source/conf.py
  examples/ar.py
  examples/nbeats.py
  examples/stallion.py
  pyproject.toml
  pytorch_forecasting/data/encoders.py
  pytorch_forecasting/data/examples.py
  pytorch_forecasting/data/samplers.py
  pytorch_forecasting/data/timeseries.py
  pytorch_forecasting/metrics/__init__.py
  pytorch_forecasting/metrics/_mqf2_utils.py
  pytorch_forecasting/metrics/base_metrics.py
  pytorch_forecasting/metrics/distributions.py
  pytorch_forecasting/metrics/point.py
  pytorch_forecasting/models/__init__.py
  pytorch_forecasting/models/base_model.py
  pytorch_forecasting/models/baseline.py
  pytorch_forecasting/models/deepar/_deepar.py
  pytorch_forecasting/models/mlp/_decodermlp.py
  pytorch_forecasting/models/mlp/submodules.py
  pytorch_forecasting/models/nbeats/__init__.py
  pytorch_forecasting/models/nbeats/_nbeats.py
  pytorch_forecasting/models/nbeats/sub_modules.py
  pytorch_forecasting/models/nhits/_nhits.py
  pytorch_forecasting/models/nhits/sub_modules.py
  pytorch_forecasting/models/nn/__init__.py
  pytorch_forecasting/models/nn/embeddings.py
  pytorch_forecasting/models/nn/rnn.py
  pytorch_forecasting/models/rnn/_rnn.py
  pytorch_forecasting/models/temporal_fusion_transformer/__init__.py
  pytorch_forecasting/models/temporal_fusion_transformer/_tft.py
  pytorch_forecasting/models/temporal_fusion_transformer/sub_modules.py
  pytorch_forecasting/models/temporal_fusion_transformer/tuning.py
  pytorch_forecasting/utils/_dependencies.py
  pytorch_forecasting/utils/_utils.py
  tests/conftest.py
  tests/test_data/test_encoders.py
  tests/test_data/test_samplers.py
  tests/test_data/test_timeseries.py
  tests/test_metrics.py
  tests/test_models/conftest.py
  tests/test_models/test_deepar.py
  tests/test_models/test_mlp.py
  tests/test_models/test_nbeats.py
  tests/test_models/test_nhits.py
  tests/test_models/test_nn/test_embeddings.py
  tests/test_models/test_nn/test_rnn.py
  tests/test_models/test_rnn_model.py
  tests/test_models/test_temporal_fusion_transformer.py
  tests/test_utils/test_show_versions.py
Labels: maintenance

#1734 Tide model interface in pytorch-forecasting.
  pytorch_forecasting/models/tide/__init__.py
  pytorch_forecasting/models/tide/sub_modules.py
Labels: enhancement

#1742 [ENH] linting tide model
  pytorch_forecasting/models/tide/__init__.py
  pytorch_forecasting/models/tide/sub_modules.py
Labels: enhancement

#1743 [ENH] move tide model - part 1
  pytorch_forecasting/models/tide/_tide.py
Labels: enhancement

#1744 [ENH] move tide model - part 2
  pytorch_forecasting/models/tide/__init__.py
  pytorch_forecasting/models/tide/_tide.py
Labels: enhancement
