Repository sktime/pytorch-forecasting, pull requests merged in 2024-11, with the labels that each got.

#1697 [MNT]`black` doesn't have `extras` dependency
  pyproject.toml
Labels: maintenance

#1699 [MNT] Remove mutable objects from defaults
  docs/source/tutorials/building.ipynb
  pytorch_forecasting/data/encoders.py
  pytorch_forecasting/data/timeseries.py
  pytorch_forecasting/metrics/base_metrics.py
  pytorch_forecasting/metrics/distributions.py
  pytorch_forecasting/metrics/point.py
  pytorch_forecasting/metrics/quantile.py
  pytorch_forecasting/models/base_model.py
  pytorch_forecasting/models/deepar/__init__.py
  pytorch_forecasting/models/mlp/__init__.py
  pytorch_forecasting/models/nbeats/__init__.py
  pytorch_forecasting/models/nhits/__init__.py
  pytorch_forecasting/models/nn/embeddings.py
  pytorch_forecasting/models/rnn/__init__.py
  pytorch_forecasting/models/temporal_fusion_transformer/__init__.py
  pytorch_forecasting/models/temporal_fusion_transformer/sub_modules.py
  pytorch_forecasting/utils/_utils.py
Labels: maintenance

#1712 [MNT] remove docs build in ci for all pr
  .github/workflows/test.yml
Labels: maintenance

#1661 [MNT] EOL for python 3.8
  .github/workflows/pypi_release.yml
  .github/workflows/test.yml
  pyproject.toml
Labels: maintenance, release

#1660 [DOC] typo fixes in changelog
  CHANGELOG.md
Labels: documentation

#1694 [BUG] fix `AttributeError: 'ExperimentWriter' object has no attribute 'add_figure'`
  pytorch_forecasting/models/base_model.py
  pytorch_forecasting/models/nbeats/__init__.py
  pytorch_forecasting/models/nhits/__init__.py
  pytorch_forecasting/models/temporal_fusion_transformer/__init__.py
Labels: bug

#1710 [MNT] CODEOWNERS file
  CODEOWNERS
Labels: maintenance

#1714 Release 1.2.0
  CHANGELOG.md
  pyproject.toml
  pytorch_forecasting/__init__.py
Labels: maintenance, release
