Repository sktime/pytorch-forecasting, pull requests merged in 2024-08, with the labels that each got.

#1598 [MNT] precommit lint step, only for changed files
  .github/workflows/lint.yml
Labels: maintenance

#1599 [MNT] Fix dependency issues and CI runners: `numpy2`, `optuna`, `requests`, MacOS MPS
  .github/workflows/test.yml
  docs/requirements.txt
  poetry.lock
  pyproject.toml
  pytorch_forecasting/data/examples.py
  pytorch_forecasting/models/base_model.py
Labels: dependencies, maintenance

#1407 [MNT] enable python 3.11 and 3.12 in package metadata and CI
  .github/workflows/test.yml
  pyproject.toml
Labels: maintenance

#1621 &felipeangelimvieira, yarnabrina [MNT] CI step to test that notebooks run
  .github/workflows/test.yml
  build_tools/run_examples.sh
  pyproject.toml
Labels: maintenance

#1615 [BUG] Fix pyproject package structure and failures in tutorial notebooks
  .github/workflows/test.yml
  docs/source/tutorials/ar.ipynb
  docs/source/tutorials/building.ipynb
  docs/source/tutorials/deepar.ipynb
  docs/source/tutorials/nhits.ipynb
  docs/source/tutorials/stallion.ipynb
  pyproject.toml
  pytorch_forecasting/__init__.py
Labels: maintenance

#1577 [BUG] remove zero from pooling_sizes and downsample_frequencies
  pytorch_forecasting/models/nhits/__init__.py
  tests/test_models/test_nhits.py
Labels: bug

#1630 [MNT] Update pre commit hooks and run all
  .pre-commit-config.yaml
  pytorch_forecasting/data/timeseries.py
Labels: maintenance

#1631 [MNT] skip tests involved in windows failures until resolved
  tests/test_models/test_temporal_fusion_transformer.py
Labels: maintenance

#1634 [MNT] remove unused imports
  examples/ar.py
  examples/nbeats.py
  examples/stallion.py
  pytorch_forecasting/data/encoders.py
  pytorch_forecasting/data/samplers.py
  pytorch_forecasting/metrics/base_metrics.py
  pytorch_forecasting/metrics/point.py
  pytorch_forecasting/metrics/quantile.py
  pytorch_forecasting/models/base_model.py
  pytorch_forecasting/models/deepar/__init__.py
  pytorch_forecasting/models/nhits/__init__.py
  pytorch_forecasting/models/nn/__init__.py
  pytorch_forecasting/models/temporal_fusion_transformer/__init__.py
  pytorch_forecasting/models/temporal_fusion_transformer/sub_modules.py
  tests/test_data/test_timeseries.py
  tests/test_metrics.py
  tests/test_models/test_deepar.py
  tests/test_models/test_mlp.py
  tests/test_models/test_nn/test_embeddings.py
  tests/test_models/test_rnn_model.py
  tests/test_models/test_temporal_fusion_transformer.py
Labels: maintenance

#1637 [MNT] isolate `cpflows` to its soft dependency set
  pyproject.toml
Labels: maintenance

#1638 [MNT] CI runs without soft dependencies
  .github/workflows/test.yml
  tests/test_models/test_nhits.py
  tests/test_models/test_temporal_fusion_transformer.py
Labels: maintenance

#1639 [MNT] make `codecov` patch coverage informational
  codecov.yml
Labels: maintenance

#1642 [MNT] rename `pytorch-optimizer` dep to `pytorch_optimizer` and raise upper bound to `<4`
  pyproject.toml
Labels: dependencies, maintenance
