Repository sktime/pytorch-forecasting, pull requests merged in 2025-01, with the labels that each got.

#1746 [ENH] clean-up refactor of `TimeSeriesDataSet`
  pytorch_forecasting/data/timeseries.py
Labels: enhancement

#1748 [MNT] Temporary fix for lint errors to conform to the recent changes in linting rules see #1749
  docs/source/conf.py
  examples/ar.py
  examples/nbeats.py
  examples/stallion.py
  pyproject.toml
  pytorch_forecasting/data/__init__.py
  pytorch_forecasting/data/encoders.py
  pytorch_forecasting/data/examples.py
  pytorch_forecasting/data/samplers.py
  pytorch_forecasting/metrics/_mqf2_utils.py
  pytorch_forecasting/metrics/base_metrics.py
  pytorch_forecasting/metrics/distributions.py
  pytorch_forecasting/metrics/point.py
  pytorch_forecasting/metrics/quantile.py
  pytorch_forecasting/models/base_model.py
  pytorch_forecasting/models/deepar/_deepar.py
  pytorch_forecasting/models/mlp/_decodermlp.py
  pytorch_forecasting/models/nbeats/_nbeats.py
  pytorch_forecasting/models/nhits/_nhits.py
  pytorch_forecasting/models/nhits/sub_modules.py
  pytorch_forecasting/models/nn/embeddings.py
  pytorch_forecasting/models/nn/rnn.py
  pytorch_forecasting/models/rnn/_rnn.py
  pytorch_forecasting/models/temporal_fusion_transformer/_tft.py
  pytorch_forecasting/models/temporal_fusion_transformer/sub_modules.py
  pytorch_forecasting/models/temporal_fusion_transformer/tuning.py
  pytorch_forecasting/models/tide/_tide.py
  pytorch_forecasting/models/tide/sub_modules.py
  pytorch_forecasting/utils/_dependencies.py
  pytorch_forecasting/utils/_utils.py
  tests/test_data/test_encoders.py
  tests/test_data/test_timeseries.py
  tests/test_models/test_deepar.py
  tests/test_models/test_mlp.py
  tests/test_models/test_nbeats.py
  tests/test_models/test_nhits.py
  tests/test_models/test_rnn_model.py
  tests/test_models/test_temporal_fusion_transformer.py
Labels: maintenance

#1667 [BUG] Bugfix when no exogenous variable is passed to TFT
  pytorch_forecasting/models/temporal_fusion_transformer/sub_modules.py
  tests/test_models/test_temporal_fusion_transformer.py
Labels: bug

#1724 [DOC] Correct argument for optimizer `ranger` in `Temporal Fusion Transformer` tutorial
  build_tools/run_examples.sh
  docs/source/conf.py
  docs/source/tutorials/stallion.ipynb
Labels: bug
