Repository sktime/pytorch-forecasting, pull requests merged in 2025-02, with the labels that each got.

#1691 [MNT] python 3.13 support
  .github/workflows/pypi_release.yml
  .github/workflows/test.yml
  pyproject.toml
Labels: maintenance, release

#1763 [DOC] minor fixes in documentation
  pyproject.toml
  pytorch_forecasting/utils/_maint/_show_versions.py
Labels: documentation

#1762 [DOC] improve and add `tide` model to docs
  docs/source/models.rst
  pytorch_forecasting/__init__.py
  pytorch_forecasting/models/__init__.py
  pytorch_forecasting/models/tide/_tide.py
  pytorch_forecasting/models/tide/sub_modules.py
Labels: documentation

#1750 [DOC] fix `gradient_clip` value in tutorials to ensure reproducible outputs similar to the committed cell output
  docs/source/tutorials/ar.ipynb
Labels: documentation

#1773 [MNT] move model base classes into `models.base` module - part 1
  pytorch_forecasting/models/__init__.py
  pytorch_forecasting/models/_base_model_rename_this.py
  pytorch_forecasting/models/base/__init__.py
  pytorch_forecasting/models/base/_base_model.py
  pytorch_forecasting/models/deepar/_deepar.py
  pytorch_forecasting/models/mlp/_decodermlp.py
  pytorch_forecasting/models/nbeats/_nbeats.py
  pytorch_forecasting/models/nhits/_nhits.py
  pytorch_forecasting/models/rnn/_rnn.py
  pytorch_forecasting/models/temporal_fusion_transformer/_tft.py
  pytorch_forecasting/models/tide/_tide.py
Labels: maintenance

#1775 [MNT] Isolate `cpflow` package, towards fixing readthedocs build
  pytorch_forecasting/metrics/_mqf2_utils.py
  pytorch_forecasting/utils/_dependencies/__init__.py
  pytorch_forecasting/utils/_dependencies/_dependencies.py
  pytorch_forecasting/utils/_dependencies/_safe_import.py
Labels: maintenance

#1777 [MNT] fix readthedocs build
  pyproject.toml
Labels: maintenance
