Repository sktime/pytorch-forecasting, pull requests merged in 2025-06, with the labels that each got.

#1861 [ENH] refactor test metadata container to include data loader configs
  pytorch_forecasting/models/deepar/_deepar_metadata.py
  pytorch_forecasting/models/nbeats/__init__.py
  pytorch_forecasting/models/nbeats/_nbeats_metadata.py
  pytorch_forecasting/models/tide/_tide_metadata.py
  pytorch_forecasting/tests/_conftest.py
  pytorch_forecasting/tests/test_all_estimators.py
  tests/test_models/test_tide.py
Labels: enhancement

#1859 [ENH] `DecoderMLP` metadata container for v1 tests
  pytorch_forecasting/models/mlp/__init__.py
  pytorch_forecasting/models/mlp/_decodermlp_metadata.py
  pytorch_forecasting/tests/_conftest.py
Labels: enhancement

#1797 [ENH] `TimeXer` model from `thuml`
  pytorch_forecasting/models/__init__.py
  pytorch_forecasting/models/timexer/__init__.py
  pytorch_forecasting/models/timexer/_timexer.py
  pytorch_forecasting/models/timexer/_timexer_metadata.py
  pytorch_forecasting/models/timexer/sub_modules.py
  tests/test_models/test_timexer.py
Labels: enhancement, new network

#1813 [ENH] EXPERIMENTAL: Example notebook based on the new data pipeline
  docs/source/tutorials/ptf_V2_example.ipynb
  pytorch_forecasting/data/examples.py
Labels: documentation

#1878 [BUG] enable silenced TFT v2 tests
  tests/test_models/test_tft_v2.py
Labels: bug, module:test_framework

#1877 [ENH] refactor test data scenario generation to `tests._data_scenarios`
  pytorch_forecasting/models/mlp/_decodermlp_metadata.py
  pytorch_forecasting/models/nbeats/_nbeats_metadata.py
  pytorch_forecasting/tests/_conftest.py
  pytorch_forecasting/tests/_data_scenarios.py
  tests/test_models/conftest.py
Labels: enhancement, module:test_framework

#1885 Release 1.4.0
  CHANGELOG.md
  pyproject.toml
  pytorch_forecasting/__init__.py
Labels: maintenance, release

#1836 [ENH] Implementing D2 data module, tests and `TimeXer` model from `tslib` for v2
  docs/source/tutorials/tslib_v2_example.ipynb
  pytorch_forecasting/data/_tslib_data_module.py
  pytorch_forecasting/data/tests/__init__.py
  pytorch_forecasting/data/tests/test_tslib_data_module.py
  pytorch_forecasting/layers/__init__.py
  pytorch_forecasting/layers/_attention/__init__.py
  pytorch_forecasting/layers/_attention/_attention_layer.py
  pytorch_forecasting/layers/_attention/_full_attention.py
  pytorch_forecasting/layers/_embeddings/__init__.py
  pytorch_forecasting/layers/_embeddings/_data_embedding.py
  pytorch_forecasting/layers/_embeddings/_en_embedding.py
  pytorch_forecasting/layers/_embeddings/_positional_embedding.py
  pytorch_forecasting/layers/_encoders/__init__.py
  pytorch_forecasting/layers/_encoders/_encoder.py
  pytorch_forecasting/layers/_encoders/_encoder_layer.py
  pytorch_forecasting/layers/_output/__init__.py
  pytorch_forecasting/layers/_output/_flatten_head.py
  pytorch_forecasting/models/base/_tslib_base_model_v2.py
  pytorch_forecasting/models/timexer/__init__.py
  pytorch_forecasting/models/timexer/_timexer_pkg_v2.py
  pytorch_forecasting/models/timexer/_timexer_v2.py
  tests/test_models/test_timexer_v2.py
Labels: enhancement
