Repository sktime/pytorch-forecasting, pull requests merged in 2025-07, with the labels that each got.

#1902 [BUG] Fix issue with `EncodeNormalizer(method='standard', center=False)` for scale value
  pytorch_forecasting/data/encoders.py
  pytorch_forecasting/models/temporal_fusion_transformer/tuning.py
  tests/test_metrics.py
Labels: bug

#1905 [BUG] fixed memory leak in `TimeSeriesDataset` by using `@cached_property` and clean-up of index construction
  pytorch_forecasting/data/timeseries/_timeseries.py
Labels: bug

#1911 [ENH] Suppress `__array_wrap__` warning in `numpy 2` for `torch` and `pandas`
  pytorch_forecasting/data/encoders.py
Labels: enhancement

#1903 [BUG] Fix issue with `plot_prediction_actual_by_variable` unsupported operand type(s) for *: 'numpy.ndarray' and 'Tensor'
  pytorch_forecasting/data/encoders.py
  tests/test_data/test_encoders.py
Labels: bug

#1915 [ENH] Suppress PyTorch deprecation warning: UserWarning: `nn.init.constant` is now deprecated in favor of `nn.init.constant_`
  pytorch_forecasting/models/dlinear/_dlinear_v2.py
Labels: maintenance

#1917 [DOC] fix minor typo in changelog
  CHANGELOG.md
Labels: documentation

#1888 [ENH] two-way linkage of model package classes and neural network classes
  pytorch_forecasting/models/base/_base_model.py
  pytorch_forecasting/models/deepar/_deepar.py
  pytorch_forecasting/models/mlp/_decodermlp.py
  pytorch_forecasting/models/nbeats/_nbeats.py
  pytorch_forecasting/models/tide/_tide.py
  pytorch_forecasting/models/timexer/_timexer.py
  pytorch_forecasting/tests/test_all_estimators.py
Labels: enhancement, API design, module:models

#1931 [BUG][DOC] Fix documentation: pass loss argument to BaseModel in custom models tutorial example
  docs/source/tutorials/building.ipynb
Labels: documentation

#1926 [BUG] fix broken version inspection if package distribution has `None` name
  pytorch_forecasting/utils/_dependencies/_dependencies.py
Labels: bug, module:test_framework

#1928 [MNT] remove import conditionals for `python 3.6`
  tests/test_models/test_temporal_fusion_transformer.py
Labels: maintenance
